# Generated by Django 5.1.4 on 2024-12-06 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('audio_file', models.FileField(upload_to='tasks/audio/')),
                ('transcription', models.TextField(blank=True, null=True)),
                ('calendar_event_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
